language: node_js
sudo: false
node_js:
  - "10"
install:
  - npm install
script:
  - cd ./src/demo && npm install && cd ../../
  - ls && npm run build
  - cd ./src && rm -r !(init.js | demo) && cd ../
  - npm login 'cherryboom'
  - ls && npm publish
